services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=bank'
      - 'MYSQL_PASSWORD=root@123'
      - 'MYSQL_ROOT_PASSWORD=root@123'
      - 'MYSQL_USER=root'
    ports:
      - '3306'