services:
  bfsm:
    build:
      context: .
    image: gchiarapa/bfsm:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bank
      SPRING_DATASOURCE_USERNAME: gt
      SPRING_DATASOURCE_PASSWORD: root@123!@
    depends_on:
      - db

  db:
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: bank
      MYSQL_ROOT_PASSWORD: root@123
      MYSQL_USER: gt
      MYSQL_PASSWORD: root@123!@
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
